In [1]:
import numpy as np
# from connect_x import ConnectX
import tensorflow as tf

In [9]:
game = ConnectX()

In [16]:
print(game.board)

[[0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [6]:
winner = game.is_done()
winner

Horizontal win 2


2